---
abstract: 'Example modules containing metadata and various example functions'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Examples
requires:
  Data::Clone: 0
  Log::Any: 0
  Rinci: v1.1.39
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Perinci-Examples
  homepage: https://metacpan.org/release/Perinci-Examples
  repository: git://github.com/sharyanto/perl-Perinci-Examples.git
version: 0.16
